/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Job Hunter API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customFetch } from './custom-fetch';
import type { ErrorType } from './custom-fetch';
export interface SearchRequest {
  /** Job title, keywords, or skills to search for */
  query: string;
  /** Location or "Remote" */
  location?: string;
}

export interface Job {
  /** Board-native job identifier */
  id: string;
  title: string;
  company: string;
  location?: string;
  /** Direct link to the job posting */
  url: string;
  /** Human-readable time since posting (e.g. "2 days ago") */
  posted_at?: string;
  /** Short description excerpt */
  snippet?: string;
  /** Job board identifier */
  source?: string;
  /** Full job description fetched from the detail page */
  description?: string;
}

export interface SourceResult {
  /** Job board identifier (e.g. "linkedin", "nofluffjobs", "professionhu") */
  source: string;
  jobs: Job[];
  /** Present when this source failed; jobs will be empty */
  error?: string;
}

export interface SearchResponse {
  sources: SourceResult[];
}

export interface ErrorResponse {
  message: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Search for job postings on configured job boards
 */
export const getSearchJobsUrl = () => {


  

  return `/api/search`
}

export const searchJobs = async (searchRequest: SearchRequest, options?: RequestInit): Promise<SearchResponse> => {
  
  return customFetch<SearchResponse>(getSearchJobsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      searchRequest,)
  }
);}
  



export const getSearchJobsMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchJobs>>, TError,{data: SearchRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof searchJobs>>, TError,{data: SearchRequest}, TContext> => {

const mutationKey = ['searchJobs'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof searchJobs>>, {data: SearchRequest}> = (props) => {
          const {data} = props ?? {};

          return  searchJobs(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SearchJobsMutationResult = NonNullable<Awaited<ReturnType<typeof searchJobs>>>
    export type SearchJobsMutationBody = SearchRequest
    export type SearchJobsMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Search for job postings on configured job boards
 */
export const useSearchJobs = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchJobs>>, TError,{data: SearchRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof searchJobs>>,
        TError,
        {data: SearchRequest},
        TContext
      > => {
      return useMutation(getSearchJobsMutationOptions(options), queryClient);
    }
