/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Job Hunter API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Search for job postings on configured job boards
 */
export const SearchJobsBody = zod.object({
  "query": zod.string().describe('Job title, keywords, or skills to search for'),
  "location": zod.string().optional().describe('Location or \"Remote\"')
})

export const SearchJobsResponse = zod.object({
  "sources": zod.array(zod.object({
  "source": zod.string().describe('Job board identifier (e.g. \"linkedin\", \"nofluffjobs\", \"professionhu\")'),
  "jobs": zod.array(zod.object({
  "id": zod.string().describe('Board-native job identifier'),
  "title": zod.string(),
  "company": zod.string(),
  "location": zod.string().optional(),
  "url": zod.string().describe('Direct link to the job posting'),
  "posted_at": zod.string().optional().describe('Human-readable time since posting (e.g. \"2 days ago\")'),
  "snippet": zod.string().optional().describe('Short description excerpt'),
  "source": zod.string().optional().describe('Job board identifier'),
  "description": zod.string().optional().describe('Full job description fetched from the detail page')
})),
  "error": zod.string().optional().describe('Present when this source failed; jobs will be empty')
}))
})
