// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// Job defines model for Job.
type Job struct {
	Company string `json:"company"`

	// Description Full job description fetched from the detail page
	Description *string `json:"description,omitempty"`

	// Id Board-native job identifier
	Id       string  `json:"id"`
	Location *string `json:"location,omitempty"`

	// PostedAt Human-readable time since posting (e.g. "2 days ago")
	PostedAt *string `json:"posted_at,omitempty"`

	// Snippet Short description excerpt
	Snippet *string `json:"snippet,omitempty"`

	// Source Job board identifier
	Source *string `json:"source,omitempty"`
	Title  string  `json:"title"`

	// Url Direct link to the job posting
	Url string `json:"url"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	// Location Location or "Remote"
	Location *string `json:"location,omitempty"`

	// Query Job title, keywords, or skills to search for
	Query string `json:"query"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Sources []SourceResult `json:"sources"`
}

// SourceResult defines model for SourceResult.
type SourceResult struct {
	// Error Present when this source failed; jobs will be empty
	Error *string `json:"error,omitempty"`
	Jobs  []Job   `json:"jobs"`

	// Source Job board identifier (e.g. "linkedin", "nofluffjobs", "professionhu")
	Source string `json:"source"`
}

// SearchJobsJSONRequestBody defines body for SearchJobs for application/json ContentType.
type SearchJobsJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search for job postings on configured job boards
	// (POST /api/search)
	SearchJobs(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Search for job postings on configured job boards
// (POST /api/search)
func (_ Unimplemented) SearchJobs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SearchJobs operation middleware
func (siw *ServerInterfaceWrapper) SearchJobs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchJobs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/search", wrapper.SearchJobs)
	})

	return r
}

type SearchJobsRequestObject struct {
	Body *SearchJobsJSONRequestBody
}

type SearchJobsResponseObject interface {
	VisitSearchJobsResponse(w http.ResponseWriter) error
}

type SearchJobs200JSONResponse SearchResponse

func (response SearchJobs200JSONResponse) VisitSearchJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchJobs400JSONResponse ErrorResponse

func (response SearchJobs400JSONResponse) VisitSearchJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchJobs500JSONResponse ErrorResponse

func (response SearchJobs500JSONResponse) VisitSearchJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Search for job postings on configured job boards
	// (POST /api/search)
	SearchJobs(ctx context.Context, request SearchJobsRequestObject) (SearchJobsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// SearchJobs operation middleware
func (sh *strictHandler) SearchJobs(w http.ResponseWriter, r *http.Request) {
	var request SearchJobsRequestObject

	var body SearchJobsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchJobs(ctx, request.(SearchJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchJobsResponseObject); ok {
		if err := validResponse.VisitSearchJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVwW4bNxD9lQHbQwtsJDVtgUA9NWiL2OghsI9RUFDLWe3YXA49nLUjGPr3gqTkWt5t",
	"0wJBbysONe/x8b3ho2l5iBwwaDLrR5PaHgdbPn8VYbnCFDkkzAtROKIoYSkPmJLdlYLuI5q1SSoUduZw",
	"aIzg3UiCzqw/PG382Jw28vYGWzWHxlzydto5M7JhP9O5MQ5TKxSVOOT62U/z2+g93PAWni1Dh9r26KAT",
	"HkB7BIdqyUPMnJopArlp47dsxb0KVukeCwA5DEodocy18NzaE8NJMXJSdH9YncK8GwcbXglaZ7ceQWlA",
	"SBRahPwnCjv4Bhe7BWzMa3B2n8DueGO+naOQAsWIMxjXPYueCYSfWpSos114lBanTS55C9usyWeEUFKP",
	"syqM4qdtfyHBVsFTuAXlcllZ7OPhpwAvjEbOnCCbJxNVqDnvXaOVtr/CuxGTTl34/BLPaf5+rAALbMwV",
	"Dqy4MaYx+MkOMR/4uDgnyd2Isp9XtFBv4Bb3DywuNbl/uiXvU1YjFbrQsZwhJQzEkt0dFIMDDDsKOHcd",
	"L9SqRP5JmL9LfnVF+STFoXx8LdiZtflq+dc4WR5nyfK67L/CNPrS/whoRex+QuvUfJbY80YTWpjn1VTZ",
	"94IJg8JDjwG0pwQVAjpLHt1P2WIJHsh72CLgEHU/d295178+cR5rk4P+tzg9RT2nAR2FjWlgYwJ3fuy6",
	"zKYuROEOUyIO/Tg7C2b1NccDTVXO+yl0XFJb41v4vRuDosDP7y9MY+5RUqW+Wny3WOWzccRgI5m1+X6x",
	"WqxMY6LVvii1tJGW1b7l1rjGLd9dydGFy3Op1C8zqUoYk75lt68PQvZ2+ZON0VON3/Im1XRW1T/rwrO4",
	"H851URmxLFTPF9qvV6svDn6MVEF/MVQoKXAHg9W2z6P+2eRLWeAfviCd86d9hs1FuLeeHMhJrsb8+H/i",
	"X7diY1ahhrS4OI3DYPPsPHolj8IzlYADtBw62o2CrpRKqlJFSCjZt2b94bE+P6ZXjevlMk9633PS9ZvV",
	"m5U5fDz8GQAA//8bEjfBFgkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
